on:
  push:
    branches:
      - masster
  pull_request:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker metadata configuration
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            jwillmer/nut-influxdbv2
          flavor: |
            latest=false
          tags: |
            type=sha
            type=semver,pattern={{version}}            
            type=raw,value=staging,enable=${{ startsWith(github.ref, 'refs/tags/v') }} 
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}    
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/master') }}   
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/main') }} 
            type=match,pattern=release-v(.*),group=1,value={{branch}},enable=${{ startsWith(github.ref, 'refs/heads/release/v') }}   
          labels: |
            github.ref=${{github.ref}}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}